package com.derun.gt3;

public class Gt3SQL {
	
	////目前提供的查询sql只有代征单位代码，没有开具完税凭证税务机关代码和税务机关名称，税务机关名称需要关联字典表查询
	StringBuffer sb1 = new StringBuffer("");    
	StringBuffer sb2 = new StringBuffer(""); 
	StringBuffer sb3 = new StringBuffer(""); 
	StringBuffer sb4 = new StringBuffer(""); 
	public Gt3SQL(Gt3InPara wsIn) {
		// TODO Auto-generated constructor stub
		sb1.append(" WITH JBXX as ( ");
		sb1.append(" select w.djxh, ");
		sb1.append(" w.nsrsbh, ");
		sb1.append(" w.CCSBDM, ");
		sb1.append(" w.CLHPHM, ");
		sb1.append(" w.CLHPZL, ");
		sb1.append(" w.CLLX, ");
		sb1.append(" w.SYRMC, ");
		sb1.append(" w.pzxh, ");
		sb1.append(" w.skssqq, ");
		sb1.append(" w.skssqz, ");
		sb1.append(" w.cclx ");
		sb1.append(" from (select ");
		
//		sb1.append("select ");
		
		sb1.append(" a.sbxxuuid, ");
		sb1.append(" c.djxh, ");
		sb1.append(" c.nsrsbh, ");
		sb1.append(" b.clsbdh CCSBDM, ");
		sb1.append(" b.clpzh CLHPHM, ");
		sb1.append(" \'\' CLHPZL, ");
		sb1.append(" \'\' CLLX, ");
		sb1.append(" c.nsrmc SYRMC, ");
		sb1.append(" a.pzxh, ");
		sb1.append(" a.skssqq, ");
		sb1.append(" a.skssqz, ");
		sb1.append(" \'0\' cclx ");
		sb1.append(" from hx_sb.sb_sysbmxbg@JS_CXK a, ");
		sb1.append(" hx_sb.sb_clqkxx@JS_CXK b, ");
		sb1.append(" hx_dj.dj_nsrxx@JS_CXK c ");
		sb1.append(" ");
		sb1.append(" where a.djxh = b.djxh ");
		sb1.append(" and a.djxh = c.djxh ");
		sb1.append(" and a.sybh_1 = b.clsbdh ");
		sb1.append(" and a.sybh_1=\'"+wsIn.getVin()+"\' ");
		sb1.append(" AND to_char(a.skssqq , \'yyyy\') = \'2016\' ");
		sb1.append(" and a.zfbz_1=\'N\' ");
		sb1.append(" and a.sybz_dm_1 =\'5\' ");
		
		sb1.append(" ");
		sb1.append(" ");
		sb1.append(" ) w ");
		sb1.append(" group by w.djxh, ");
		sb1.append(" w.nsrsbh, ");
		sb1.append(" w.ccsbdm, ");
		sb1.append(" w.clhphm, ");
		sb1.append(" w.clhpzl, ");
		sb1.append(" w.cllx, ");
		sb1.append(" w.cclx, ");
		sb1.append(" w.syrmc, ");
		sb1.append(" w.pzxh, ");
		sb1.append(" w.skssqq, ");
		sb1.append(" w.skssqz ");
		sb1.append(" ) ");
		sb1.append(" select ");
		sb1.append(" ");
		sb1.append(" tpl.id_sequences.nextval, ");
		sb1.append(" jbxx.nsrsbh NSRSBH, ");
		sb1.append(" jbxx.ccsbdm CCSBDM, ");
		sb1.append(" jbxx.clhphm CLHPHM, ");
		sb1.append(" jbxx.clhpzl CLHPZL, ");
		sb1.append(" jbxx.cllx CLLX, ");
		sb1.append(" ");
		sb1.append(" jbxx.syrmc SYRMC, ");
		sb1.append(" jbxx.skssqq SKSSQQ, ");
		sb1.append(" jbxx.skssqz SKSSQZ, ");
		sb1.append(" yj.ybtse JNJE, ");
		sb1.append(" yj.yzclrq WSRQ, ");
		sb1.append(" jks.zsswjg_dm dzdwdm, ");
		sb1.append(" nvl(jks.pzhm, jks.dzsphm) WSPZH, ");
		sb1.append(" sysdate SJCJRQ ");
		sb1.append(" from hx_zs.zs_yjsf@JS_CXK yj, jbxx, hx_zs.zs_jks@JS_CXK jks ");
		sb1.append(" ");
		sb1.append(" where ");
		sb1.append(" yj.zsxm_dm=\'10114\' ");
		sb1.append(" and jks.zsxm_dm=\'10114\' ");
		sb1.append(" and yj.skzl_dm=\'10\' ");
		sb1.append(" AND to_char(yj.skssqq , \'yyyy\') = \'2016\' ");
		sb1.append(" ");
		sb1.append(" ");
		sb1.append(" ");
		sb1.append(" and yj.yzpzxh = jbxx.pzxh ");
		sb1.append(" AND yj.skssqq = jbxx.skssqq ");
		sb1.append(" AND yj.skssqz = jbxx.skssqz ");
		sb1.append(" AND jbxx.ccsbdm = yj.sybh_1 ");
		sb1.append(" AND yj.sybh_1 = \'"+wsIn.getVin()+"\' ");
		sb1.append(" and yj.tzlx_dm in (\'1\', \'4\') ");
		sb1.append(" and jks.tzlx_dm in (\'1\', \'4\') ");
		sb1.append(" and yj.skcllx_dm=\'1\' ");
		sb1.append(" and yj.yzclrq is not null ");
		sb1.append(" and yj.zsuuid = jks.zsuuid (+) ");
//		sb.append(" ");
		sb2.append(" with jbxx as ");
		sb2.append(" ( ");
		sb2.append(" ");
		sb2.append(" ");
		sb2.append(" select w.djxh, ");
		sb2.append(" w.nsrsbh, ");
		sb2.append(" w.CCSBDM, ");
		sb2.append(" w.CLHPHM, ");
		sb2.append(" w.CLHPZL, ");
		sb2.append(" w.CLLX, ");
		sb2.append(" w.SYRMC, ");
		sb2.append(" w.pzxh, ");
		sb2.append(" w.skssqq, ");
		sb2.append(" w.skssqz, ");
		sb2.append(" w.cclx ");
		sb2.append(" from (select ");
		
//		sb2.append(" select ");
		
		sb2.append(" a.sbxxuuid, ");
		sb2.append(" c.djxh, ");
		sb2.append(" c.nsrsbh, ");
		sb2.append(" b.clsbdh CCSBDM, ");
		sb2.append(" b.clpzh CLHPHM, ");
		sb2.append(" \'\' CLHPZL, ");
		sb2.append(" \'\' CLLX, ");
		sb2.append(" c.nsrmc SYRMC, ");
		sb2.append(" a.pzxh, ");
		sb2.append(" a.skssqq, ");
		sb2.append(" a.skssqz, ");
		sb2.append(" \'0\' cclx ");
		sb2.append(" from hx_sb.sb_sysbmxbg@JS_CXK a, ");
		sb2.append(" hx_sb.sb_clqkxx@JS_CXK b, ");
		sb2.append(" hx_dj.dj_nsrxx@JS_CXK c ");
		sb2.append(" ");
		sb2.append(" where a.djxh = b.djxh ");
		sb2.append(" and a.djxh = c.djxh ");
		sb2.append(" and a.sybh_1 = b.clsbdh ");
		sb2.append(" and a.sybh_1=\'"+wsIn.getVin()+"\' ");
		sb2.append(" AND to_char(a.skssqq , \'yyyy\') = \'2016\' ");
		sb2.append(" and a.zfbz_1=\'N\' ");
		sb2.append(" and a.sybz_dm_1 =\'5\' ");
		
		sb2.append(" ");
		sb2.append(" ");
		sb2.append(" ) w ");
		sb2.append(" group by w.djxh, ");
		sb2.append(" w.nsrsbh, ");
		sb2.append(" w.ccsbdm, ");
		sb2.append(" w.clhphm, ");
		sb2.append(" w.clhpzl, ");
		sb2.append(" w.cllx, ");
		sb2.append(" w.cclx, ");
		sb2.append(" w.syrmc, ");
		sb2.append(" w.pzxh, ");
		sb2.append(" w.skssqq, ");
		sb2.append(" w.skssqz ");
		sb2.append(" ) ");
		sb2.append(" select ");
		sb2.append(" tpl.id_sequences.nextval, ");
		sb2.append(" jbxx.nsrsbh NSRSBH, ");
		sb2.append(" jbxx.ccsbdm CCSBDM, ");
		sb2.append(" jbxx.clhphm CLHPHM, ");
		sb2.append(" jbxx.clhpzl CLHPZL, ");
		sb2.append(" jbxx.cllx CLLX, ");
		sb2.append(" ");
		sb2.append(" jbxx.syrmc SYRMC, ");
		sb2.append(" jbxx.skssqq SKSSQQ, ");
		sb2.append(" jbxx.skssqz SKSSQZ, ");
		sb2.append(" yj.ybtse JNJE, ");
		sb2.append(" yj.yzclrq WSRQ, ");
		sb2.append(" jks.zsswjg_dm dzdwdm, ");
		sb2.append(" nvl(jks.pzhm, jks.dzsphm) WSPZH, ");
		sb2.append(" sysdate SJCJRQ ");
		sb2.append(" from hx_zs.zs_yjsf@JS_CXK yj, jbxx, hx_zs.zs_wsz@JS_CXK jks ");
		sb2.append(" ");
		sb2.append(" where ");
		sb2.append(" yj.zsxm_dm=\'10114\' ");
		sb2.append(" ");
		sb2.append(" and yj.skzl_dm=\'10\' ");
		sb2.append(" AND to_char(yj.skssqq , \'yyyy\') = \'2016\' ");
		sb2.append(" and yj.yzpzxh = jbxx.pzxh ");
		sb2.append(" AND yj.skssqq = jbxx.skssqq ");
		sb2.append(" AND yj.skssqz = jbxx.skssqz ");
		sb2.append(" AND jbxx.ccsbdm = yj.sybh_1 ");
		sb2.append(" AND yj.sybh_1 = \'"+wsIn.getVin()+"\' ");
		sb2.append(" and yj.tzlx_dm in (\'1\', \'4\') ");
		sb2.append(" and jks.tzlx_dm in (\'1\', \'4\') ");
		sb2.append(" and yj.skcllx_dm=\'1\' ");
		sb2.append(" and yj.yzclrq is not null ");
		sb2.append(" and yj.zsuuid = jks.zsuuid (+) ");
//		sb.append(" ");
		sb3.append(" with jbxx as ");
		sb3.append(" ( ");
		sb3.append(" ");
		sb3.append(" ");
		sb3.append(" select w.djxh, ");
		sb3.append(" w.nsrsbh, ");
		sb3.append(" w.CCSBDM, ");
		sb3.append(" w.CLHPHM, ");
		sb3.append(" w.CLHPZL, ");
		sb3.append(" w.CLLX, ");
		sb3.append(" w.SYRMC, ");
		sb3.append(" w.pzxh, ");
		sb3.append(" w.skssqq, ");
		sb3.append(" w.skssqz, ");
		sb3.append(" w.cclx ");
		sb3.append(" from (select ");
		
//		sb3.append(" select ");
		
		sb3.append(" a.sbxxuuid, ");
		sb3.append(" c.djxh, ");
		sb3.append(" c.nsrsbh, ");
		sb3.append(" b.clsbdh CCSBDM, ");
		sb3.append(" b.clpzh CLHPHM, ");
		sb3.append(" \'\' CLHPZL, ");
		sb3.append(" \'\' CLLX, ");
		sb3.append(" c.XM SYRMC, ");
		sb3.append(" a.pzxh, ");
		sb3.append(" a.skssqq, ");
		sb3.append(" a.skssqz, ");
		sb3.append(" \'0\' cclx ");
		sb3.append(" from hx_sb.sb_sysbmxbg@JS_CXK a, ");
		sb3.append(" hx_sb.sb_clqkxx@JS_CXK b, ");
		sb3.append(" gs_cxtj.dj_zrr@JS_CXK c ");
		sb3.append(" ");
		sb3.append(" where a.djxh = b.djxh ");
		sb3.append(" and a.djxh = c.djxh ");
		sb3.append(" and a.sybh_1 = b.clsbdh ");
		sb3.append(" and a.sybh_1=\'"+wsIn.getVin()+"\' ");
		sb3.append(" AND to_char(a.skssqq , \'yyyy\') = \'2016\' ");
		sb3.append(" and a.zfbz_1=\'N\' ");
		sb3.append(" and a.sybz_dm_1 =\'5\' ");
		
		sb3.append(" ");
		sb3.append(" ");
		sb3.append(" ) w ");
		sb3.append(" group by w.djxh, ");
		sb3.append(" w.nsrsbh, ");
		sb3.append(" w.ccsbdm, ");
		sb3.append(" w.clhphm, ");
		sb3.append(" w.clhpzl, ");
		sb3.append(" w.cllx, ");
		sb3.append(" w.cclx, ");
		sb3.append(" w.syrmc, ");
		sb3.append(" w.pzxh, ");
		sb3.append(" w.skssqq, ");
		sb3.append(" w.skssqz ");
		sb3.append(" ) ");
		sb3.append(" select ");
		sb3.append(" ");
		sb3.append(" tpl.id_sequences.nextval, ");
		sb3.append(" jbxx.nsrsbh NSRSBH, ");
		sb3.append(" jbxx.ccsbdm CCSBDM, ");
		sb3.append(" jbxx.clhphm CLHPHM, ");
		sb3.append(" jbxx.clhpzl CLHPZL, ");
		sb3.append(" jbxx.cllx CLLX, ");
		sb3.append(" ");
		sb3.append(" jbxx.syrmc SYRMC, ");
		sb3.append(" jbxx.skssqq SKSSQQ, ");
		sb3.append(" jbxx.skssqz SKSSQZ, ");
		sb3.append(" yj.ybtse JNJE, ");
		sb3.append(" yj.yzclrq WSRQ, ");
		sb3.append(" jks.zsswjg_dm dzdwdm, ");
		sb3.append(" nvl(jks.pzhm, jks.dzsphm) WSPZH, ");
		sb3.append(" sysdate SJCJRQ ");
		sb3.append(" from hx_zs.zs_yjsf@JS_CXK yj, jbxx, hx_zs.zs_jks@JS_CXK jks ");
		sb3.append(" ");
		sb3.append(" where ");
		sb3.append(" yj.zsxm_dm=\'10114\' ");
		sb3.append(" and jks.zsxm_dm=\'10114\' ");
		sb3.append(" and yj.skzl_dm=\'10\' ");
		sb3.append(" AND to_char(yj.skssqq , \'yyyy\') = \'2016\' ");
		sb3.append(" ");
		sb3.append(" ");
		sb3.append(" ");
		sb3.append(" and yj.yzpzxh = jbxx.pzxh ");
		sb3.append(" AND yj.skssqq = jbxx.skssqq ");
		sb3.append(" AND yj.skssqz = jbxx.skssqz ");
		sb3.append(" AND jbxx.ccsbdm = yj.sybh_1 ");
		sb3.append(" AND yj.sybh_1 = \'"+wsIn.getVin()+"\' ");
		sb3.append(" and yj.tzlx_dm in (\'1\', \'4\') ");
		sb3.append(" and jks.tzlx_dm in (\'1\', \'4\') ");
		sb3.append(" and yj.skcllx_dm=\'1\' ");
		sb3.append(" and yj.yzclrq is not null ");
		sb3.append(" and yj.zsuuid = jks.zsuuid (+) ");
//		sb.append(" ");
		sb4.append(" with jbxx as ");
		sb4.append(" ( ");
		sb4.append(" ");
		sb4.append(" ");
		sb4.append(" select w.djxh, ");
		sb4.append(" w.nsrsbh, ");
		sb4.append(" w.CCSBDM, ");
		sb4.append(" w.CLHPHM, ");
		sb4.append(" w.CLHPZL, ");
		sb4.append(" w.CLLX, ");
		sb4.append(" w.SYRMC, ");
		sb4.append(" w.pzxh, ");
		sb4.append(" w.skssqq, ");
		sb4.append(" w.skssqz, ");
		sb4.append(" w.cclx ");
		sb4.append(" from (select ");
		
//		sb4.append(" select ");
		
		sb4.append(" a.sbxxuuid, ");
		sb4.append(" c.djxh, ");
		sb4.append(" c.nsrsbh, ");
		sb4.append(" b.clsbdh CCSBDM, ");
		sb4.append(" b.clpzh CLHPHM, ");
		sb4.append(" \'\' CLHPZL, ");
		sb4.append(" \'\' CLLX, ");
		sb4.append(" c.XM SYRMC, ");
		sb4.append(" a.pzxh, ");
		sb4.append(" a.skssqq, ");
		sb4.append(" a.skssqz, ");
		sb4.append(" \'0\' cclx ");
		sb4.append(" from hx_sb.sb_sysbmxbg@JS_CXK a, ");
		sb4.append(" hx_sb.sb_clqkxx@JS_CXK b, ");
		sb4.append(" gs_cxtj.dj_zrr@JS_CXK c ");
		sb4.append(" ");
		sb4.append(" where a.djxh = b.djxh ");
		sb4.append(" and a.djxh = c.djxh ");
		sb4.append(" and a.sybh_1 = b.clsbdh ");
		sb4.append(" and a.sybh_1=\'"+wsIn.getVin()+"\' ");
		sb4.append(" AND to_char(a.skssqq , \'yyyy\') = \'2016\' ");
		sb4.append(" and a.zfbz_1=\'N\' ");
		sb4.append(" and a.sybz_dm_1 =\'5\' ");
		
		sb4.append(" ");
		sb4.append(" ) w ");
		sb4.append(" group by w.djxh, ");
		sb4.append(" w.nsrsbh, ");
		sb4.append(" w.ccsbdm, ");
		sb4.append(" w.clhphm, ");
		sb4.append(" w.clhpzl, ");
		sb4.append(" w.cllx, ");
		sb4.append(" w.cclx, ");
		sb4.append(" w.syrmc, ");
		sb4.append(" w.pzxh, ");
		sb4.append(" w.skssqq, ");
		sb4.append(" w.skssqz ");
		sb4.append(" ) ");
		sb4.append(" select ");
		sb4.append(" ");
		sb4.append(" tpl.id_sequences.nextval, ");
		sb4.append(" jbxx.nsrsbh NSRSBH, ");
		sb4.append(" jbxx.ccsbdm CCSBDM, ");
		sb4.append(" jbxx.clhphm CLHPHM, ");
		sb4.append(" jbxx.clhpzl CLHPZL, ");
		sb4.append(" jbxx.cllx CLLX, ");
		sb4.append(" ");
		sb4.append(" jbxx.syrmc SYRMC, ");
		sb4.append(" jbxx.skssqq SKSSQQ, ");
		sb4.append(" jbxx.skssqz SKSSQZ, ");
		sb4.append(" yj.ybtse JNJE, ");
		sb4.append(" yj.yzclrq WSRQ, ");
		sb4.append(" jks.zsswjg_dm dzdwdm, ");
		sb4.append(" nvl(jks.pzhm, jks.dzsphm) WSPZH, ");
		sb4.append(" sysdate SJCJRQ ");
		sb4.append(" from hx_zs.zs_yjsf@JS_CXK yj, jbxx, hx_zs.zs_wsz@JS_CXK jks ");
		sb4.append(" ");
		sb4.append(" where yj.zsxm_dm=\'10114\' ");
		sb4.append(" ");
		sb4.append(" and yj.skzl_dm=\'10\' ");
		sb4.append(" AND to_char(yj.skssqq , \'yyyy\') = \'2016\' ");
		sb4.append(" ");
		sb4.append(" and yj.yzpzxh = jbxx.pzxh ");
		sb4.append(" AND yj.skssqq = jbxx.skssqq ");
		sb4.append(" AND yj.skssqz = jbxx.skssqz ");
		sb4.append(" AND jbxx.ccsbdm = yj.sybh_1 ");
		sb4.append(" AND yj.sybh_1 = \'"+wsIn.getVin()+"\' ");
		sb4.append(" and yj.tzlx_dm in (\'1\', \'4\') ");
		sb4.append(" and jks.tzlx_dm in (\'1\', \'4\') ");
		sb4.append(" and yj.skcllx_dm=\'1\' ");
		sb4.append(" and yj.yzclrq is not null ");
		sb4.append(" and yj.zsuuid = jks.zsuuid (+); ");
		
	}
	

	public static void main(String[] args) {
		Gt3InPara wsIn = new Gt3InPara();
		wsIn.setVin("LZWACAGA9A4181610");
		Gt3SQL gt3sql = new Gt3SQL(wsIn);
		System.out.println(gt3sql.sb1.toString());
	}

}
